// GENERATED BY DARWIN
import React from 'react';

export default function App() {
  return (
    <div style={{ position: 'relative', width: '100vw', height: '100vh', overflow: 'hidden', backgroundColor: 'white' }}>
      <nav style={{ position: 'absolute', left: 0, top: 0, width: 450, height: 64, backgroundColor: '#ffffff', display: 'flex', alignItems: 'center', padding: '0 24px', boxSizing: 'border-box' }}>
        <h1 style={{ fontWeight: 'bold', margin: 0 }}>Startup.io</h1>
      </nav>
      <h1 style={{ position: 'absolute', left: 40, top: 140, width: 350, height: 100, fontSize: '3.5rem', color: '#000', margin: 0, lineHeight: 1 }}>
        Build Faster.
      </h1>
      <button style={{ position: 'absolute', left: 136, top: 246, width: 140, height: 48, backgroundColor: '#000', borderRadius: '8px', color: 'white', fontWeight: 'bold', border: 'none', cursor: 'pointer' }}>
        Get Started
      </button>
    </div>
  );
}